---
title: "SVM"
author: "Wan-Lun Tsai"
date: "April 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(e1071)
library(sparsediscrim)
library(rattle)
library(ggplot2)
library(reshape2)
library(grid)
library(gridExtra)
library(corrplot)
library(dplyr)
library(plyr)
library(caret)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
spam_train=read.table('D:/STATS503/HW/spam-train.txt',sep=',')
spam_test=read.table('D:/STATS503/HW/spam-test.txt',sep=',')
etype=factor(spam_train[,58])
standard_spam=data.frame(cbind(scale(spam_train[,1:57]),etype))
```

```{r}
ggpairs(as.data.frame(spam_train[1:5],mapping=ggplot2::aes(colour=Y),title='training data'))
ggpairs(as.data.frame(spam_test[1:5],mapping=ggplot2::aes(colour=Y),title=paste('test data')))
ggplot(spam_train,aes(x=factor(V58)))+geom_histogram(stat='count')
ggplot(spam_test,aes(x=factor(V58)))+geom_histogram(stat='count')
```

```{r}
set.seed(1070)
folds=cv_partition(standard_spam[,58], num_folds = 5)
error_svm_radial= function(costC) {
  spam.svm = svm(factor(etype)~.,data=standard_spam,kernel='radial',cost=costC)
  train_error = sum(spam.svm$fitted !=standard_spam[,58]) / nrow(standard_spam)
  test_error = sum(predict(spam.svm, spam_test) != spam_test[,58]) / nrow(spam_test)
  spam.cverr = sapply(folds, function(fold) {
    svmcv = svm(factor(etype)~.,data=standard_spam,kernel='radial', cost=costC, subset = fold$training)
    svmpred = predict(svmcv, standard_spam[fold$test,])
    return(sum(svmpred != standard_spam[,58][fold$test]) / length(fold$test))
  })
  cv_error = mean(spam.cverr)
  return(c(train_error, cv_error, test_error))
}
radial_cost_errors=sapply(costs,function(cost) error_svm_radial(cost))
svm_radial_errs = data.frame(costs,t(radial_cost_errors))
colnames(svm_radial_errs) = c('Radialcosts','Train', 'CV', 'Test')
grid.arrange(tableGrob(svm_radial_errs))
dataRadial=melt(svm_radial_errs, id="Radialcosts")
ggplot(dataRadial,aes_string(x="Radialcosts", y="value", colour="variable",group="variable", linetype="variable", shape="variable")) +geom_line(size=1) + labs(x = "Cost",y = "Classification error",colour="",group="", linetype="",shape="",title="Standardized SVM Error, Kernel: Radial") + scale_x_log10()
```
 
```{r}
set.seed(1070)
folds=cv_partition(spam_train[,58], num_folds = 5)
error_svm_radial= function(costC) {
  spam.svm = svm(factor(etype)~.,data=spam_train,kernel='radial',cost=costC)
  train_error = sum(spam.svm$fitted !=spam_train[,58]) / nrow(spam_train)
  test_error = sum(predict(spam.svm, spam_test) != spam_test[,58]) / nrow(spam_test)
  spam.cverr = sapply(folds, function(fold) {
    svmcv = svm(factor(etype)~.,data=spam_train,kernel='radial', cost=costC, subset = fold$training)
    svmpred = predict(svmcv, spam_train[fold$test,])
    return(sum(svmpred != spam_train[,58][fold$test]) / length(fold$test))
  })
  cv_error = mean(spam.cverr)
  return(c(train_error, cv_error, test_error))
}
radial_cost_errors=sapply(costs,function(cost) error_svm_radial(cost))
svm_radial_errs = data.frame(costs,t(radial_cost_errors))
colnames(svm_radial_errs) = c('Radialcosts','Train', 'CV', 'Test')
grid.arrange(tableGrob(svm_radial_errs))
dataRadial=melt(svm_radial_errs, id="Radialcosts")
ggplot(dataRadial,aes_string(x="Radialcosts", y="value", colour="variable",group="variable", linetype="variable", shape="variable")) +geom_line(size=1) + labs(x = "Cost",y = "Classification error",colour="",group="", linetype="",shape="",title="Original SVM Error, Kernel: Radial") + scale_x_log10()
```





